project:
  type: book
  preview:
    port: 4201
    browser: true
  render:
  - '*.md'
  - '*.qmd'
  - '!LICENSE.md'
  - '!README.md'
  output-dir: ../docs
  pre-render: scripts/render_children.R
  post-render: _extensions/inbo/flandersqmd-book/filters/post_render.R
execute:
  echo: false
  warnings: true
  errors: true
  message: true
  freeze: false
  cache: false
format:
  flandersqmd-book-html: default
  flandersqmd-book-pdf: default
lang: nl-BE
flandersqmd:
  entity: INBO
  level: 2
  title: Grote grazers in beeld
  subtitle: Een data-rapport over terreingebruik in Vlaamse natuurgebieden
  shorttitle: grote-grazers
  author:
  - name:
      given: Marijke
      family: Thoonen
    email: marijke.thoonen@inbo.be
    orcid: 0000-0002-0305-5029
    affiliation:
    - Instituut voor Natuur- en Bosonderzoek (INBO)
    corresponding: true
  reviewer:
  - name:
      given: Ra√Øsa
      family: Carmen
    email: raisa.carmen@inbo.be
    orcid: 0000-0003-1025-8702
    affiliation:
    - Instituut voor Natuur- en Bosonderzoek (INBO)
  public_report: true
  colophon: true
  floatbarrier: section
book:
  downloads: pdf
  open-graph: true
  body-footer: '{{< footer >}}'
  navbar:
    pinned: true
    right:
    - icon: mastodon
      href: https://mastodon.online/&#64;inbo
    - icon: bluesky
      href: https://bsky.app/profile/inbo.be
    - icon: facebook
      href: https://www.facebook.com/INBOVlaanderen/
    left:
    - text: Cover
      file: index.md
    - text: Aanbevelingen
      file: aanbevelingen.md
    - text: Inleiding
      file: 1_inleiding.qmd
    - text: Resultaten
      file: 2_resultaten.qmd
  chapters:
  - index.md
  - abstract.md
  - aanbevelingen.md
  - 1_inleiding.qmd
  - 2_resultaten.qmd
  - referenties.md
bibliography: references.bib
